DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  item TEXT NOT NULL,
  protein TEXT NOT NULL,
  energy TEXT NOT NULL,
  carbs TEXT NOT NULL,
  fat TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
